#version: "3.8"
version: "2"

services:
  openvpn:
    image: den4ik7707/den_openvpn:1.2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1717:1194"
    volumes:
      - .:/usr/openvpn
#    command: openvpn --config ./server/server.conf
    command: sh -c "openvpn --config ./server/server.conf && sleep infinity"
