#version: "3.8"
version: "2"

services:
  openvpn:
    image: den4ik7707/den_openvpn:1.4
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1717:1194/udp"
    volumes:
      - .:/usr/openvpn
    restart: always
    command: >
      /bin/sh -c "iptables -A FORWARD -i tun0 -j ACCEPT &&
                  iptables -A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
                  iptables -A FORWARD -i eth0 -o tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
                  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
                  openvpn --config ./server/server.conf &&
                  sleep infinity"
